[build]
  base = "frontend"
  command = "npm run build"
  publish = "build"

[build.environment]
  CI = "false"
  NODE_VERSION = "18"
  REACT_APP_BACKEND_URL = "https://restaurant-saas-backend-fbbd.onrender.com"
  REACT_APP_API_URL = "https://restaurant-saas-backend-fbbd.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
